### ISSUE TITLE
proposed change: star count for each relay/project on GitHub

### ISSUE THREAD

**Issue by pox** [aljazceru/awesome-nostr#101]
It's hard to tell, at a glance, which projects are more popular than others. If the GitHub stars of each were visible next to each it would be super helpful.

e.g. just for illustration

### Implementations

- [NNostr](https://github.com/Kukks/NNostr) - a C# relay ![stars](https://img.shields.io/github/stars/Kukks/NNostr.svg?style=social)
- [nostr-rs-relay](https://sr.ht/~gheartsfield/nostr-rs-relay/) - a minimalistic relay written in Rust that saves data on SQLite 
- [Relayer Basic](https://github.com/fiatjaf/relayer/tree/master/basic) - a simple relay based on _relayer_ backed by Postgres ![stars](https://img.shields.io/github/stars/fiatjaf/relayer.svg?style=social)
- [nodestr](https://github.com/Dolu89/nodestr-relay) - a Node.js implementation ![stars](https://img.shields.io/github/stars/Dolu89/nodestr-relay.svg?style=social)

The above star badges are live, by the way.

If you like this idea, I don't mind doing the work on adding stars to all github repo links. Just let me know what you think.

There are also a few possible star styles if you don't like the above design. You can see them here: https://shields.io/category/social

**Comment by aljazceru** [comment]
@pox nice idea, I have similar ideas for nostr.net but for now i've added the stars to every github repo link to see how ppl like it

**Comment by pox** [comment]
Your rock!
🙏
