### ISSUE TITLE
Java library is missing

### ISSUE THREAD

**Issue by Giszmo** [aljazceru/awesome-nostr#16]
This is a dummy issue to hopefully connect with others who need a Java library. I will share my progress here as soon as I get to writing one myself and would love to see others share their progress, too.

**Comment by Giszmo** [comment]
Want to join? Is Kotlin fine with you? I need it for Android which is Kotlin nowadays.

**Comment by 0xtrr** [comment]
I don't have any experience with Kotlin yet but I'm a quick learner so I could try to play around with Kotlin a bit over the weekend and see if I can learn the basics. If so, I would be more than happy to help out wherever I can!

**Comment by Giszmo** [comment]
A library was born ...

Work in progress very much but I already get Events over websocket as they happen:

https://github.com/Giszmo/NostrPostr

**Comment by aljazceru** [comment]
@Giszmo @0xtrr java library now exists https://github.com/tcheeric/nostr-java

**Comment by Giszmo** [comment]
For what it's worth, my NostrPostr is being used in production in my relay implementation in the same repo. It also [does support nip-04](https://github.com/Giszmo/NostrPostr/blob/a872c7768cd93d12c76ab14b62d9df3fae8fe1fe/nostrpostrlib/src/test/java/nostr/postr/events/EncryptedDmEventTest.kt). Have to update the readme.

**Comment by Giszmo** [comment]
So nostr-java and NostrPostr are both JVM libraries. The former is listed under clients. @aljazceru you might want to fix that. Either way, this issue has run its cause.
