### ISSUE TITLE
Remove archived/404 repos.

### ISSUE THREAD

**Issue by gourcetools** [aljazceru/awesome-nostr#238]
I've found that some repos are not available or archived.

Archived: Dolu89/nodestr-relay
Archived: fiatjaf/expensive-relay
Archived: futurepaul/nostr-rs
Archived: fiatjaf/branle
404: fiatjaf/rsslay
404: lightningorb/nostrify.me

Also if you can add if they meet requierements: 

NostrAirTracker : Elonjet on Nostr
https://github.com/gourcetools/NostrAirTracker

NostReply : Bot that reply to specified text on nostr global feed using NIP50
https://github.com/gourcetools/nostreply

Spamster : Spamster is for testing relays and spam filters.
https://github.com/gourcetools/spamster

**Comment by aljazceru** [comment]
its time to do some archived/deprecated review again yeah, will curate it a bit

**Comment by aljazceru** [comment]
@gourcetools  thanks for this (feel free to just PR next time), i've added your tools (love the elonjet) and updated the archived/deleted ones

**Comment by gourcetools** [comment]
Thank you,  sorry no PR. :(
 Next time!
