### ISSUE TITLE
add earthly to clients

### ISSUE THREAD

**Issue by moogmodular** [aljazceru/awesome-nostr#387]
`- [earthly](https://github.com/moogmodular/earthly)![stars](https://img.shields.io/github/stars/moogmodular/earthly.svg?style=social) - A social geojson editor with maps on Nostr
`

thx

**Comment by AsaiToshiya** [comment]
I think just the PR is fine for this.

**Comment by moogmodular** [comment]
https://github.com/aljazceru/awesome-nostr/pull/390
