### ISSUE TITLE
Add Nostrame(Nostr Account Manager Extension)

### ISSUE THREAD

**Issue by Anderson-Juhasc** [aljazceru/awesome-nostr#420]
Hi,

I'm developing this chromium extension, but I'm not sure in witch category it goes, maybe Tools, Nostr account manager or Nostr Wallet.
Feedback and ideas are welcome.

https://github.com/Anderson-Juhasc/nostrame

Thanks!

**Comment by AsaiToshiya** [comment]
For now, I think it would be good to add to the Tools section.

**Comment by aljazceru** [comment]
added to tools section
